[2024-09-06T19:45:52.248-0500] {processor.py:186} INFO - Started process (PID=34800) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:45:52.250-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:45:52.250-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:45:52.250-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:45:52.267-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:45:52.264-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:45:52.267-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:45:52.267-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:45:52.267-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:45:52.305-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-09-06T19:48:14.020-0500] {processor.py:186} INFO - Started process (PID=35363) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:48:14.022-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:48:14.023-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:48:14.023-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:48:14.040-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:48:14.037-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:48:14.040-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:48:14.040-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:48:14.040-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:48:14.080-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-09-06T19:50:05.050-0500] {processor.py:186} INFO - Started process (PID=35716) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:50:05.052-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:50:05.052-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:50:05.052-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:50:05.069-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:50:05.066-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:50:05.069-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:50:05.069-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:50:05.069-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:50:05.108-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T19:52:47.178-0500] {processor.py:186} INFO - Started process (PID=36225) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:52:47.180-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:52:47.180-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:52:47.180-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:52:47.197-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:52:47.194-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:52:47.197-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:52:47.197-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:52:47.197-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:52:47.236-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T19:54:36.700-0500] {processor.py:186} INFO - Started process (PID=36622) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:54:36.703-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:54:36.703-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:54:36.703-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:54:36.718-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:54:36.716-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:54:36.719-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:54:36.719-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:54:36.719-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:54:36.755-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-09-06T19:56:28.196-0500] {processor.py:186} INFO - Started process (PID=36988) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:56:28.198-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:56:28.198-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:56:28.198-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:56:28.216-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:56:28.213-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:56:28.216-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:56:28.216-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:56:28.216-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:56:28.258-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-09-06T19:59:12.743-0500] {processor.py:186} INFO - Started process (PID=37488) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:59:12.745-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T19:59:12.746-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:59:12.746-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:59:12.764-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:59:12.761-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T19:59:12.765-0500] {logging_mixin.py:190} INFO - [2024-09-06T19:59:12.765-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T19:59:12.765-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T19:59:12.804-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-09-06T20:01:54.848-0500] {processor.py:186} INFO - Started process (PID=37993) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:01:54.849-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:01:54.850-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:01:54.850-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:01:54.866-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:01:54.863-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:01:54.866-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:01:54.866-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:01:54.866-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:01:54.904-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-09-06T20:04:33.635-0500] {processor.py:186} INFO - Started process (PID=38484) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:04:33.637-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:04:33.638-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:04:33.638-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:04:33.656-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:04:33.654-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:04:33.656-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:04:33.656-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:04:33.657-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:04:33.698-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-09-06T20:07:16.004-0500] {processor.py:186} INFO - Started process (PID=38977) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:07:16.007-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:07:16.007-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:07:16.007-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:07:16.024-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:07:16.021-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:07:16.024-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:07:16.024-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:07:16.024-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:07:16.061-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-09-06T20:10:02.458-0500] {processor.py:186} INFO - Started process (PID=39504) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:10:02.460-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:10:02.460-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:10:02.460-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:10:02.478-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:10:02.475-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:10:02.478-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:10:02.478-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:10:02.478-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:10:02.516-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T20:12:43.849-0500] {processor.py:186} INFO - Started process (PID=40034) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:12:43.852-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:12:43.852-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:12:43.852-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:12:43.869-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:12:43.867-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:12:43.869-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:12:43.869-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:12:43.870-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:12:43.907-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T20:15:59.879-0500] {processor.py:186} INFO - Started process (PID=40716) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:15:59.881-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:15:59.882-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:15:59.882-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:15:59.899-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:15:59.896-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:15:59.899-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:15:59.899-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:15:59.899-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:15:59.938-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T20:22:50.872-0500] {processor.py:186} INFO - Started process (PID=42939) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:22:50.874-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:22:50.874-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:22:50.874-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:22:50.892-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:22:50.889-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:22:50.892-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:22:50.892-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:22:50.892-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:22:50.935-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-09-06T20:24:41.968-0500] {processor.py:186} INFO - Started process (PID=43279) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:24:41.971-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:24:41.971-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:24:41.971-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:24:41.989-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:24:41.986-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:24:41.990-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:24:41.990-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:24:41.990-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:24:42.031-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-09-06T20:27:55.653-0500] {processor.py:186} INFO - Started process (PID=43937) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:27:55.655-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:27:55.655-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:27:55.655-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:27:55.676-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:27:55.673-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:27:55.676-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:27:55.676-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:27:55.676-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:27:55.725-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2024-09-06T20:29:49.127-0500] {processor.py:186} INFO - Started process (PID=44324) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:29:49.129-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:29:49.130-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:29:49.130-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:29:49.146-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:29:49.143-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:29:49.146-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:29:49.146-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:29:49.146-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:29:49.185-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-09-06T20:32:31.048-0500] {processor.py:186} INFO - Started process (PID=44845) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:32:31.051-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:32:31.051-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:32:31.051-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:32:31.068-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:32:31.065-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:32:31.068-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:32:31.068-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:32:31.068-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:32:31.107-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T20:34:28.535-0500] {processor.py:186} INFO - Started process (PID=45231) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:34:28.537-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:34:28.538-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:34:28.538-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:34:28.554-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:34:28.552-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:34:28.555-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:34:28.554-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:34:28.555-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:34:28.594-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-06T20:36:20.687-0500] {processor.py:186} INFO - Started process (PID=45599) to work on /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:36:20.690-0500] {processor.py:914} INFO - Processing file /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-06T20:36:20.690-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:36:20.690-0500] {dagbag.py:587} INFO - Filling up the DagBag from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:36:20.707-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:36:20.704-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-06T20:36:20.707-0500] {logging_mixin.py:190} INFO - [2024-09-06T20:36:20.707-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-06T20:36:20.707-0500] {processor.py:927} WARNING - No viable dags retrieved from /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-06T20:36:20.745-0500] {processor.py:208} INFO - Processing /Users/binhpham/Library/Python/3.9/lib/python/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
